In [56]:
import pandas as pd
import numpy as np
students = pd.DataFrame({
    "Student_ID":[101,102,102,103,104,105],
    "Name":["Tej","Ujjawal","Yash","Yogesh","Ujjawal ", None],
    "Dept":["CSE","cse","cse","Data Science","DATA SCIENCE","ECE"],
    "Marks":[85,72,72,np.nan,88,91],
    "Attendance":[90,82,82,75,np.nan,88],
    "Exam_Date":["2026-09-01","01/09/2026","01/09/2026","2026-09-02",
                 "not known","20266-09-03"]
})
print(students)

   Student_ID      Name          Dept  Marks  Attendance    Exam_Date
0         101       Tej           CSE   85.0        90.0   2026-09-01
1         102   Ujjawal           cse   72.0        82.0   01/09/2026
2         102      Yash           cse   72.0        82.0   01/09/2026
3         103    Yogesh  Data Science    NaN        75.0   2026-09-02
4         104  Ujjawal   DATA SCIENCE   88.0         NaN    not known
5         105      None           ECE   91.0        88.0  20266-09-03

In [57]:
students.isnull()

   Student_ID   Name   Dept  Marks  Attendance  Exam_Date
0       False  False  False  False       False      False
1       False  False  False  False       False      False
2       False  False  False  False       False      False
3       False  False  False   True       False      False
4       False  False  False  False        True      False
5       False   True  False  False       False      False

In [58]:
students.isna()

   Student_ID   Name   Dept  Marks  Attendance  Exam_Date
0       False  False  False  False       False      False
1       False  False  False  False       False      False
2       False  False  False  False       False      False
3       False  False  False   True       False      False
4       False  False  False  False        True      False
5       False   True  False  False       False      False

In [59]:
students.isnull().values.any()

np.True_

In [60]:
students.isnull().sum()

Student_ID    0
Name          1
Dept          0
Marks         1
Attendance    1
Exam_Date     0
dtype: int64

In [61]:
missing_percent = students.isnull().mean()*100
print(missing_percent.round(2))

Student_ID     0.00
Name          16.67
Dept           0.00
Marks         16.67
Attendance    16.67
Exam_Date      0.00
dtype: float64

#Removing Missing Values with dropna()

In [62]:
df_clean = students.dropna()
print(df_clean)

   Student_ID     Name Dept  Marks  Attendance   Exam_Date
0         101      Tej  CSE   85.0        90.0  2026-09-01
1         102  Ujjawal  cse   72.0        82.0  01/09/2026
2         102     Yash  cse   72.0        82.0  01/09/2026

In [63]:
df_clean = students.dropna(axis=1)
print(df_clean)

   Student_ID          Dept    Exam_Date
0         101           CSE   2026-09-01
1         102           cse   01/09/2026
2         102           cse   01/09/2026
3         103  Data Science   2026-09-02
4         104  DATA SCIENCE    not known
5         105           ECE  20266-09-03

In [64]:
students

   Student_ID      Name          Dept  Marks  Attendance    Exam_Date
0         101       Tej           CSE   85.0        90.0   2026-09-01
1         102   Ujjawal           cse   72.0        82.0   01/09/2026
2         102      Yash           cse   72.0        82.0   01/09/2026
3         103    Yogesh  Data Science    NaN        75.0   2026-09-02
4         104  Ujjawal   DATA SCIENCE   88.0         NaN    not known
5         105      None           ECE   91.0        88.0  20266-09-03

In [65]:
df_clean = students.dropna(how="all")
print(df_clean)

   Student_ID      Name          Dept  Marks  Attendance    Exam_Date
0         101       Tej           CSE   85.0        90.0   2026-09-01
1         102   Ujjawal           cse   72.0        82.0   01/09/2026
2         102      Yash           cse   72.0        82.0   01/09/2026
3         103    Yogesh  Data Science    NaN        75.0   2026-09-02
4         104  Ujjawal   DATA SCIENCE   88.0         NaN    not known
5         105      None           ECE   91.0        88.0  20266-09-03

In [66]:
clean = students.copy()
clean["Marks"] = clean["Marks"].fillna(clean["Marks"].mean())
clean["Attendance"] = clean["Attendance"].fillna(clean["Attendance"].mean())
clean["Name"] = clean["Name"].fillna("Unknown")
print(clean[["Name","Marks","Attendance"]])

       Name  Marks  Attendance
0       Tej   85.0        90.0
1   Ujjawal   72.0        82.0
2      Yash   72.0        82.0
3    Yogesh   81.6        75.0
4  Ujjawal    88.0        83.4
5   Unknown   91.0        88.0

In [67]:
clean = students.copy()
clean["Marks"] = clean["Marks"].fillna(clean["Marks"].median())
clean["Attendance"] = clean["Attendance"].fillna(clean["Attendance"].median())
clean["Name"] = clean["Name"].fillna("Unknown")
print(clean[["Name","Marks","Attendance"]])

       Name  Marks  Attendance
0       Tej   85.0        90.0
1   Ujjawal   72.0        82.0
2      Yash   72.0        82.0
3    Yogesh   85.0        75.0
4  Ujjawal    88.0        82.0
5   Unknown   91.0        88.0

#Simple Statistical Imputation

#Mean Imputation

In [68]:
from sklearn.impute import SimpleImputer
df_mean = students.copy()
mean_imputer = SimpleImputer(strategy="mean")
df_mean[["Marks","Attendance"]] = mean_imputer.fit_transform(df_mean[["Marks","Attendance"]])
print(df_mean[["Marks","Attendance"]])

   Marks  Attendance
0   85.0        90.0
1   72.0        82.0
2   72.0        82.0
3   81.6        75.0
4   88.0        83.4
5   91.0        88.0

#Median Imputation

In [69]:
from sklearn.impute import SimpleImputer
df_median = students.copy()
median_imputer = SimpleImputer(strategy="median")
df_median[["Marks","Attendance"]] = median_imputer.fit_transform(df_median[["Marks","Attendance"]])
print(df_median[["Marks","Attendance"]])

   Marks  Attendance
0   85.0        90.0
1   72.0        82.0
2   72.0        82.0
3   85.0        75.0
4   88.0        82.0
5   91.0        88.0

#Mode Imputation

In [70]:
from sklearn.impute import SimpleImputer
df_mode = students.copy()
mode_imputer = SimpleImputer(missing_values=None,strategy="most_frequent")
df_mode[["Name"]] = mode_imputer.fit_transform(df_mode[["Name"]])
print(df_mode)

   Student_ID      Name          Dept  Marks  Attendance    Exam_Date
0         101       Tej           CSE   85.0        90.0   2026-09-01
1         102   Ujjawal           cse   72.0        82.0   01/09/2026
2         102      Yash           cse   72.0        82.0   01/09/2026
3         103    Yogesh  Data Science    NaN        75.0   2026-09-02
4         104  Ujjawal   DATA SCIENCE   88.0         NaN    not known
5         105       Tej           ECE   91.0        88.0  20266-09-03

#Constant Imputation

In [71]:
from sklearn.impute import SimpleImputer
df_const = students.copy()
constant_imputer = SimpleImputer(strategy="constant",fill_value=0)
df_const[["Marks","Attendance"]] = constant_imputer.fit_transform(df_const[["Marks","Attendance"]])
print(df_const)

   Student_ID      Name          Dept  Marks  Attendance    Exam_Date
0         101       Tej           CSE   85.0        90.0   2026-09-01
1         102   Ujjawal           cse   72.0        82.0   01/09/2026
2         102      Yash           cse   72.0        82.0   01/09/2026
3         103    Yogesh  Data Science    0.0        75.0   2026-09-02
4         104  Ujjawal   DATA SCIENCE   88.0         0.0    not known
5         105      None           ECE   91.0        88.0  20266-09-03

#KNN Imputation

In [72]:
from sklearn.impute import KNNImputer
df_knn = students.copy()
knn_imputer = KNNImputer(n_neighbors=2)
df_knn[["Marks","Attendance"]] = knn_imputer.fit_transform(df_knn[["Marks","Attendance"]])
print(df_knn)

   Student_ID      Name          Dept  Marks  Attendance    Exam_Date
0         101       Tej           CSE   85.0        90.0   2026-09-01
1         102   Ujjawal           cse   72.0        82.0   01/09/2026
2         102      Yash           cse   72.0        82.0   01/09/2026
3         103    Yogesh  Data Science   72.0        75.0   2026-09-02
4         104  Ujjawal   DATA SCIENCE   88.0        89.0    not known
5         105      None           ECE   91.0        88.0  20266-09-03

#Remove Exact Duplicate Rows

In [73]:
print("Exact duplicates:", clean.duplicated().sum())
no_exact_duplicates = clean.drop_duplicates()
print("Rows before:",len(clean))
print("Rows after:",len(no_exact_duplicates))
print("After removing exact duplicates:", no_exact_duplicates.shape[0])

Exact duplicates: 0
Rows before: 6
Rows after: 6
After removing exact duplicates: 6

#Remove duplicates using an ID

In [74]:
unique_students = no_exact_duplicates.drop_duplicates(
    subset=["Student_ID"], keep="first"
)
print("Rows before:",len(no_exact_duplicates))
print("Rows after:",len(unique_students))
print("After removing duplicates:", unique_students.shape[0])
print(unique_students[["Student_ID","Name","Dept"]])

Rows before: 6
Rows after: 5
After removing duplicates: 5
   Student_ID      Name          Dept
0         101       Tej           CSE
1         102   Ujjawal           cse
3         103    Yogesh  Data Science
4         104  Ujjawal   DATA SCIENCE
5         105   Unknown           ECE

#Fix Inconsistent text

In [75]:
unique_students = unique_students.copy()
unique_students["Name"] = unique_students["Name"].str.strip().str.title()
print(unique_students["Name"])

0        Tej
1    Ujjawal
3     Yogesh
4    Ujjawal
5    Unknown
Name: Name, dtype: object

In [76]:
unique_students["Dept"] = unique_students["Dept"].str.lower()
print(unique_students["Dept"])

0             cse
1             cse
3    data science
4    data science
5             ece
Name: Dept, dtype: object

In [77]:
dept_map = {
    "cse":"CSE",
    "ece":"ECE",
    "data science":"Data Science"
}
unique_students["Dept"] = unique_students["Dept"].map(dept_map).fillna("Needs review")
print(unique_students[["Name","Dept"]])

      Name          Dept
0      Tej           CSE
1  Ujjawal           CSE
3   Yogesh  Data Science
4  Ujjawal  Data Science
5  Unknown           ECE

#Convert dates and check ranges

In [78]:
unique_students["Exam_Date"] = pd.to_datetime(unique_students["Exam_Date"], errors="coerce",dayfirst=True)
print(unique_students["Exam_Date"])

0   2026-01-09
1          NaT
3   2026-02-09
4          NaT
5          NaT
Name: Exam_Date, dtype: datetime64[ns]

In [79]:
print("Missing or invalid dates:", unique_students["Exam_Date"].isnull().sum())

Missing or invalid dates: 3

In [80]:
bad_marks = unique_students[~unique_students["Marks"].between(0,100)]
print("Marks outside 0-100")
print(bad_marks)

Marks outside 0-100
Empty DataFrame
Columns: [Student_ID, Name, Dept, Marks, Attendance, Exam_Date]
Index: []